env                       = "dev"
env_profile               = "default"
env_region                = "us-east-1"
stack_name                = "lambda"
public_network_cidr_base  = "10.20"
private_network_cidr_base = "10.10"
